name: frontend-project-11 check

on:
  - push
  - pull_request

env:
  CI: true

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
    
      matrix:
        node-version: [18.x]

    steps:

      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies, build the project
        run: |
          npm ci
          npm run build:prod

        env:
          CI: true

      - name: Run linter
        run: make lint